#!/usr/bin/env bash
#
# sync_to_companion.sh
#
# Ship the eight Section 7 / validation CSVs and the shared math primitives
# (scripts/paper_pipeline/lib/) from pef-empirical to the sibling
# pef-mathematics repo, and stamp a manifest with sha256 + source commit
# so the companion paper can cite exact provenance.
#
# Usage:
#   bash scripts/paper_pipeline/sync_to_companion.sh
#
# Default sibling location:
#   <empirical_root>/../pef-mathematics
# Override with the PEF_MATHEMATICS_DIR environment variable.
#
# Exit codes:
#   0  success (manifest written, files copied)
#   1  bad invocation (missing CSV, sibling not found, etc.)

set -euo pipefail

# ---- 0. Locate self, empirical root, sibling -------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EMPIRICAL_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
OUTPUTS_DIR="${SCRIPT_DIR}/outputs"
LIB_SRC="${SCRIPT_DIR}/lib"

DEFAULT_SIBLING="$(cd "${EMPIRICAL_ROOT}/.." && pwd)/pef-mathematics"
COMPANION_DIR="${PEF_MATHEMATICS_DIR:-${DEFAULT_SIBLING}}"

VAL_INPUTS_DIR="${COMPANION_DIR}/validation_inputs"
LIB_MIRROR_DIR="${COMPANION_DIR}/scripts/lib"
MANIFEST="${VAL_INPUTS_DIR}/_manifest.csv"
PREV_MANIFEST_TMP=""

# ---- 1. Pre-flight checks --------------------------------------------------
if [[ ! -d "${COMPANION_DIR}/.git" ]]; then
    echo "error: companion repo not found at ${COMPANION_DIR}" >&2
    echo "       set PEF_MATHEMATICS_DIR to override the default location." >&2
    exit 1
fi
if [[ ! -d "${OUTPUTS_DIR}" ]]; then
    echo "error: pipeline outputs directory missing: ${OUTPUTS_DIR}" >&2
    echo "       run scripts/paper_pipeline/run_paper_pipeline.m first." >&2
    exit 1
fi
if [[ ! -d "${LIB_SRC}" ]]; then
    echo "error: shared library directory missing: ${LIB_SRC}" >&2
    exit 1
fi

# The eight CSVs that feed pef-mathematics/validation_inputs/.
CSVS=(
    "kappa_symmetry_audit.csv"
    "kappa_symmetry_nonsports.csv"
    "pef_landscape_2season_geometry.csv"
    "psi_per_domain.csv"
    "psi_heterogeneity.csv"
    "psi_ml_residuals.csv"
    "domain_summary.csv"
    "table_numbers.csv"
)

missing=()
for f in "${CSVS[@]}"; do
    if [[ ! -f "${OUTPUTS_DIR}/${f}" ]]; then
        missing+=("${f}")
    fi
done
if (( ${#missing[@]} > 0 )); then
    echo "error: required pipeline outputs missing from ${OUTPUTS_DIR}:" >&2
    printf '       - %s\n' "${missing[@]}" >&2
    echo "       re-run scripts/paper_pipeline/run_paper_pipeline.m." >&2
    exit 1
fi

# ---- 2. Capture empirical provenance ---------------------------------------
pushd "${EMPIRICAL_ROOT}" > /dev/null
EMPIRICAL_SHA="$(git rev-parse HEAD 2>/dev/null || echo 'unknown')"
if [[ -n "$(git status --porcelain 2>/dev/null)" ]]; then
    EMPIRICAL_DIRTY="dirty"
else
    EMPIRICAL_DIRTY="clean"
fi
popd > /dev/null

SYNC_TS_UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# ---- 3. Snapshot previous manifest (for diff reporting) --------------------
if [[ -f "${MANIFEST}" ]]; then
    PREV_MANIFEST_TMP="$(mktemp)"
    cp "${MANIFEST}" "${PREV_MANIFEST_TMP}"
fi

mkdir -p "${VAL_INPUTS_DIR}"
mkdir -p "${LIB_MIRROR_DIR}"

# ---- 4. Copy the eight CSVs ------------------------------------------------
echo "Syncing ${#CSVS[@]} CSVs -> ${VAL_INPUTS_DIR}"
for f in "${CSVS[@]}"; do
    cp "${OUTPUTS_DIR}/${f}" "${VAL_INPUTS_DIR}/${f}"
done

# ---- 5. Mirror shared library (read-only audit copy) -----------------------
echo "Mirroring ${LIB_SRC} -> ${LIB_MIRROR_DIR}"
# Wipe then copy to avoid stale files when entries are renamed/removed upstream.
find "${LIB_MIRROR_DIR}" -maxdepth 1 -type f \( -name '*.m' -o -name 'README.md' \) -delete 2>/dev/null || true
for src in "${LIB_SRC}"/*.m; do
    [[ -f "${src}" ]] || continue
    cp "${src}" "${LIB_MIRROR_DIR}/$(basename "${src}")"
done

cat > "${LIB_MIRROR_DIR}/README.md" <<EOF
# Shared PEF math primitives (read-only mirror)

> Auto-generated by \`sync_to_companion.sh\` in
> [pef-empirical](https://github.com/AroundInteger/pef-empirical) at commit
> \`${EMPIRICAL_SHA}\` (${EMPIRICAL_DIRTY}, ${SYNC_TS_UTC}).
>
> **Do not edit files in this directory.** Edit the authoritative copy in
> \`pef-empirical/scripts/paper_pipeline/lib/\` and re-run
> \`bash scripts/paper_pipeline/sync_to_companion.sh\`.

This mirror exists so reviewers of the companion §7 numerical validation can
inspect the exact MATLAB primitives (\`eta_pef\`, \`classify_quadrant\`,
\`mi_closed\`, ...) that produced \`validation_inputs/*.csv\` without needing
to clone the empirical repo.
EOF

# ---- 6. Write manifest -----------------------------------------------------
{
    echo "filename,sha256,source_commit,empirical_dirty,source_path,synced_at_utc"
    for f in "${CSVS[@]}"; do
        sha="$(shasum -a 256 "${VAL_INPUTS_DIR}/${f}" | awk '{print $1}')"
        echo "${f},${sha},${EMPIRICAL_SHA},${EMPIRICAL_DIRTY},scripts/paper_pipeline/outputs/${f},${SYNC_TS_UTC}"
    done
} > "${MANIFEST}"

# ---- 7. Diff against previous manifest (best-effort) -----------------------
if [[ -n "${PREV_MANIFEST_TMP}" ]]; then
    echo ""
    echo "Change summary (vs previous manifest):"
    changed=0
    unchanged=0
    new=0
    for f in "${CSVS[@]}"; do
        new_sha="$(awk -F, -v name="${f}" '$1==name{print $2}' "${MANIFEST}")"
        old_sha="$(awk -F, -v name="${f}" '$1==name{print $2}' "${PREV_MANIFEST_TMP}")"
        if [[ -z "${old_sha}" ]]; then
            echo "  + ${f}  (new entry)"
            new=$((new + 1))
        elif [[ "${old_sha}" == "${new_sha}" ]]; then
            unchanged=$((unchanged + 1))
        else
            echo "  ~ ${f}  (sha256 changed)"
            changed=$((changed + 1))
        fi
    done
    echo "  summary: ${changed} changed, ${unchanged} unchanged, ${new} new"
    rm -f "${PREV_MANIFEST_TMP}"
else
    echo ""
    echo "No previous manifest found; this is the first sync."
fi

# ---- 8. Done ---------------------------------------------------------------
echo ""
echo "Sync complete."
echo "  Empirical commit : ${EMPIRICAL_SHA} (${EMPIRICAL_DIRTY})"
echo "  Companion target : ${COMPANION_DIR}"
echo "  Manifest         : ${MANIFEST}"
if [[ "${EMPIRICAL_DIRTY}" == "dirty" ]]; then
    echo ""
    echo "  WARNING: empirical working tree was dirty when sync ran."
    echo "  Commit pending changes in pef-empirical before claiming provenance."
fi
